/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_n1ar4_jar_obfuscator_jvmti_CodeEncryptor */

#ifndef _Included_me_n1ar4_jar_obfuscator_jvmti_CodeEncryptor
#define _Included_me_n1ar4_jar_obfuscator_jvmti_CodeEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_n1ar4_jar_obfuscator_jvmti_CodeEncryptor
 * Method:    encrypt
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_n1ar4_jar_obfuscator_jvmti_CodeEncryptor_encrypt
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
